[project]
requires-python = ">=3.6"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "ninja",
    "scikit-build @ git+https://github.com/scikit-build/scikit-build@master",
]
