name: Build dev wheels

on:
  workflow_dispatch:

jobs:
  setup_date:
    name: Setup version timestamp
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.date.outputs.now }}
    steps:
    - id: date 
      run: echo "::set-output name=now::$(date +'%Y%m%d%H%M')"

  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    needs: setup_date
    env:
      TWEEDLEDUM_DEV_VERSION: ${{needs.setup_date.outputs.timestamp}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade scikit-build

      - name: Build sdist
        run: |
          python setup.py sdist --dist-dir=wheelhouse

      - name: Upload built sdist
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.tar.gz

  build_wheels_linux:
    name: Wheels • Linux
    runs-on: ubuntu-latest
    needs: setup_date

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CIBW_SKIP: cp27-* cp34-* cp35-* pp*
          CIBW_ENVIRONMENT: "TWEEDLEDUM_DEV_VERSION=${{needs.setup_date.outputs.timestamp}}"
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/python/test/ -t {project}
          CMAKE_BUILD_PARALLEL_LEVEL: 2

      - name: Upload built wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_wheels_macos_10_15:
    name: Wheels • MacOS (10.15+)
    runs-on: macos-latest
    needs: setup_date

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CIBW_SKIP: cp27-* cp34-* cp35-* pp*
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ENVIRONMENT: "TWEEDLEDUM_DEV_VERSION=${{needs.setup_date.outputs.timestamp}}"
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/python/test/ -t {project}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
          MACOSX_DEPLOYMENT_TARGET: '10.15'

      - name: Upload built wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_wheels_macos_10_9:
    name: Wheels • MacOS (10.9+)
    runs-on: macos-latest
    needs: setup_date

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CIBW_SKIP: cp27-* cp34-* cp35-* pp*
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ENVIRONMENT: "TWEEDLEDUM_DEV_VERSION=${{needs.setup_date.outputs.timestamp}} CC=gcc-10 CXX=g++-10 CXXFLAGS='-static-libgcc -static-libstdc++'"
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/python/test/ -t {project}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
          MACOSX_DEPLOYMENT_TARGET: '10.9'

      - name: Upload built wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_wheels_windows64:
    name: Wheels • Windows (64-bits)
    runs-on: windows-latest
    needs: setup_date

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.5.0

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CC: cl.exe
          CXX: cl.exe 
          CIBW_SKIP: cp27-* cp34-* cp35-* pp* *-win32
          CIBW_ENVIRONMENT: "TWEEDLEDUM_DEV_VERSION=${{needs.setup_date.outputs.timestamp}}"
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/python/test/ -t {project}
          CMAKE_BUILD_PARALLEL_LEVEL: 2

      - name: Upload built wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_wheels_windows32:
    name: Wheels • Windows (32-bits)
    runs-on: windows-latest
    needs: setup_date

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.5.0
        with:
            arch: x86

      - name: Build wheel
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CC: cl.exe
          CXX: cl.exe
          CIBW_BUILD: cp3{6,7,8,9}*-win32
          CIBW_ENVIRONMENT: "TWEEDLEDUM_DEV_VERSION=${{needs.setup_date.outputs.timestamp}}"
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/python/test/ -t {project}
          CMAKE_BUILD_PARALLEL_LEVEL: 2

      - name: Upload built wheel 
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
