name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    env:
      CIBW_SKIP: cp27-* pp27-*
      CIBW_BEFORE_BUILD: python -m pip install --upgrade cmake ninja scikit-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.2
   
    - uses: ilammy/msvc-dev-cmd@v1.2.0
      if: startsWith(matrix.os, 'windows')

    - name: Build wheel for windows
      if: startsWith(matrix.os, 'windows')
      env:
          CC: cl.exe
          CXX: cl.exe
          CIBW_SKIP: pp27-* cp27-* *-win32
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - name: Build wheel
      if: ${{ !(startsWith(matrix.os, 'windows')) }}
      env:
          CIBW_SKIP: pp27-* cp27-*
      run: |
        python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse