name: Coverage CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - '**/CMakeLists.txt'
      - '**.cpp'
      - '**.h'
      - 'tests/**'
      - 'external/**'

jobs:
  build-ubuntu:
    name: Build and run codecov
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      env:
        CC: gcc-9
        CXX: g++-9
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DTWEEDLEDUM_TESTS=ON \
          -DTWEEDLEDUM_ENABLE_COVERAGE=ON

    - name: Build tests
      working-directory: build
      run: make -j2 run_tests

    - name: Run tests
      run: |
        cd build
        ./tests.run_tests

    - name: Run lcov
      run: |
        sudo apt-get install lcov
        lcov -t "result" -o lcov.info -c -d .
        lcov -e lcov.info "*tweedledum/include*" "*tweedledum/lib*"  -o lcov_filtered.info
        lcov -l lcov_filtered.info

    - name: CodeCov
      run: |
        bash <(curl -s https://codecov.io/bash) -f lcov_filtered.info || echo "Codecov did not collect coverage reports"
