name: Python tests

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - '**/CMakeLists.txt'
      - '**.cpp'
      - '**.h'
      - '**.py'
      - 'external/**'

jobs:
  tests:
    name: ${{ matrix.os }} • Py${{ matrix.python-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.9.0
        if: runner.os == 'Windows'

      - name: Set Windows variables
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "CC=cl.exe" >> $GITHUB_ENV
          echo "CXX=cl.exe" >> $GITHUB_ENV

      - name: Install from source
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install .

      - name: Run tests
        run: |
          pytest --import-mode importlib -v python/test/
