name: Wheels

on:
  pull_request:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.9.0
        env:
          CIBW_SKIP: cp27-* cp34-* cp35-* pp* *win32
          CIBW_ARCHS_MACOS: x86_64 universal2
          MACOSX_DEPLOYMENT_TARGET: '10.15'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl